I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scenario.rpy", line 7889, in script
    play music eli fadein 2
  File "renpy/common/000statements.rpy", line 123, in execute_play_music
    renpy.music.play(_audio_eval(p["file"]),
  File "renpy/common/000statements.rpy", line 32, in _audio_eval
    return eval(expr, locals=store.audio.__dict__)
  File "game/scenario.rpy", line 7889, in <module>
    play music eli fadein 2
NameError: name 'eli' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scenario.rpy", line 7889, in script
    play music eli fadein 2
  File "/media/bergen/DATA/renpy-7.4.11-sdk/renpy/ast.py", line 2015, in execute
    self.call("execute")
  File "/media/bergen/DATA/renpy-7.4.11-sdk/renpy/ast.py", line 2003, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "/media/bergen/DATA/renpy-7.4.11-sdk/renpy/statements.py", line 278, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 123, in execute_play_music
    renpy.music.play(_audio_eval(p["file"]),
  File "renpy/common/000statements.rpy", line 32, in _audio_eval
    return eval(expr, locals=store.audio.__dict__)
  File "/media/bergen/DATA/renpy-7.4.11-sdk/renpy/python.py", line 2276, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/media/bergen/DATA/renpy-7.4.11-sdk/renpy/python.py", line 2269, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/scenario.rpy", line 7889, in <module>
    play music eli fadein 2
NameError: name 'eli' is not defined

Linux-5.15.0-56-generic-x86_64-with-debian-bookworm-sid
Ren'Py 7.4.11.2266
Skitetsky REMASTER 1.0
Fri Mar  3 19:25:19 2023
